- id: '1518189920099'
  alias: Alarm home night
  trigger:
  - at: '23:00:00'
    platform: time
  - at: '23:59:00'
    platform: time
  - at: 01:00:00
    platform: time
  - at: 02:00:00
    platform: time
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: disarmed
  action:
  - data:
      code: 5381
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_home
- id: '1518189941152'
  alias: Alarm off morning
  trigger:
  - at: 05:30:00
    platform: time
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_home
  action:
  - data:
      code: 5381
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
- id: '1519128635267'
  alias: Master bedroom prepare evening
  trigger:
  - at: '21:00:00'
    platform: time
  condition: []
  action:
  - data:
      brightness_pct: 25
      entity_id: light.bedroom
    service: light.turn_on
- id: '1526624082837'
  alias: Leave home (alarm on ask)
  trigger:
  - entity_id: device_tracker.google_maps_116101876784266767195
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: state
    entity_id: alarm_control_panel.tallgatan_alarm
    state: disarmed
  action:
  - data:
      data:
        actions:
        - action: alarm_on
          icon: /static/icons/favicon-192x192.png
          title: Larma på
      message: Du lämnar hemmet och har glömt att larma, vill du larma på?
      title: Larma på?
    service: notify.html5_push
- id: '1526626906212'
  alias: Alarm away
  trigger:
  - event_data:
      action: alarm_on
    event_type: html5_notification.clicked
    platform: event
  condition: []
  action:
  - data:
      code: 5381
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away
- id: '1526629850759'
  alias: Alarm off
  trigger:
  - event_data:
      action: alarm_off
    event_type: html5_notification.clicked
    platform: event
  condition: []
  action:
  - data:
      code: 5381
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
- id: alarm_armed_away
  alias: '[Alarm] Away Mode Armed'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_away
  action:
  - data:
      data:
        tag: alarm_armed_away_notification
      message: Larmet är påslaget och igång (Away mode)
      title: Larmat
    service: notify.mobile_app_victor_ohrstrom_s_lya_l29
  - data:
      gw_mac: 04:CF:8C:91:60:79
      ringtone_id: 10002
      ringtone_vol: 100
    service: xiaomi_aqara.play_ringtone
- id: alarm_armed_home
  alias: '[Alarm] Home Mode Armed'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_home
  action: []
- id: alarm_arming_away
  alias: '[Alarm] Away Mode Arming'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: pending
  action: []
- id: alarm_disarmed
  alias: '[Alarm] Disarmed'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: disarmed
  action:
  - data:
      data:
        tag: alarm_disarmed_notification
      message: Välkommen hem!
      title: Avlarmat
    service: notify.mobile_app_victor_ohrstrom_s_lya_l29
  - data:
      gw_mac: 04:CF:8C:91:60:79
      ringtone_id: 10001
      ringtone_vol: 30
    service: xiaomi_aqara.play_ringtone
- id: alarm_triggered
  alias: '[Alarm] Triggered'
  trigger: []
  action: []
- id: alarm_warning
  alias: '[Alarm] Warning'
  trigger: []
  action:
  - data:
      data:
        actions:
        - action: alarm_off
          icon: /static/icons/favicon-192x192.png
          title: Ja
      message: Välkommen hem, vill du larma av?
      title: Larma av?
    service: notify.html5_push
- id: alarm_off_push
  alias: '[Alarm] Disarm push action'
  trigger:
  - event_data:
      action: alarm_off
    event_type: html5_notification.clicked
    platform: event
  condition: []
  action:
  - data:
      code: 5381
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
- id: '1548781915262'
  alias: Alarm push ask disarm
  trigger: []
  condition: []
  action:
  - data:
      data:
        actions:
        - action: alarm_off
          icon: /static/icons/favicon-192x192.png
          title: Ja
      message: Välkommen hem, vill du larma av?
      title: Larma av?
    service: notify.html5_push
- id: '1549453451905'
  alias: Kitchen button double press
  trigger:
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_kitchen
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      brightness_pct: 100
      entity_id: light.koket
    service: light.turn_on
- id: '1549453503292'
  alias: Kitchen button long press
  trigger:
  - event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_kitchen
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      code: 5381
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away
- id: '1518016636265'
  alias: Kitchen button single press
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_kitchen
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      brightness_pct: 1
      entity_id: light.koket
    service: light.turn_on
- id: office_button_double
  alias: Bedroom button double press
  trigger:
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_office
    event_type: xiaomi_aqara.click
    platform: event
  action:
  - data:
      brightness_pct: 100
      entity_id: light.bedroom
    service: light.turn_on
- id: office_button_long
  alias: Bedroom button long press
  trigger:
  - event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_office
    event_type: xiaomi_aqara.click
    platform: event
  action:
  - data:
      entity_id: light.bedroom
    service: light.turn_off
- id: office_button_single
  alias: Bedroom button single press
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_office
    event_type: xiaomi_aqara.click
    platform: event
  action:
  - data:
      brightness_pct: 1
      entity_id: light.bedroom
    service: light.turn_on
- id: '1551114672155'
  alias: Kitchen turn off strip
  trigger:
  - entity_id: light.koket
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.kitchen_strip
    service: light.turn_off
- id: '1564665925166'
  alias: Test ikea remote
  trigger:
  - entity_id: sensor.bedroom_remote
    platform: state
  condition: []
  action:
  - data:
      entity_id: light.office
    service: light.toggle
- id: '1565203371505'
  alias: Liam trigger night
  trigger:
  - entity_id: light.liam_fonster
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '23:00:00'
    before: 05:00:00
    condition: time
  action:
  - data:
      brightness_pct: 1
      entity_id: light.sovrum_2
    service: light.turn_on
  - data:
      brightness_pct: '1'
      entity_id: light.hall_1, light.hall_2, light.hall_3, light.hall_4
    service: light.turn_on
- id: '1565203602936'
  alias: Liam trigger night off
  trigger:
  - entity_id: light.liam_fonster
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '23:00:00'
    before: 05:00:00
    condition: time
  action:
  - data:
      entity_id: light.sovrum_2
    service: light.turn_off
  - data:
      entity_id: light.hall_1, light.hall_2, light.hall_3, light.hall_4
    service: light.turn_off
- id: '1572341136263'
  alias: Välkommen hem
  description: När min mobil kommer hem
  trigger:
  - event: enter
    platform: geo_location
    source: device_tracker.victor
    zone: zone.hem
  condition: []
  action:
  - data:
      data:
        actions:
        - action: alarm_off
          icon: /static/icons/favicon-192x192.png
          title: Ja
      message: Välkommen hem, larma av?
      title: Larma av?
    service: notify.mobile_app_victor_ohrstrom_s_lya_l29
- id: '1574871299562'
  alias: Leave home
  description: ''
  trigger:
  - entity_id: device_tracker.dc_16_b2_af_85_73
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: test tracker
      title: test
    service: notify.mobile_app_victor_ohrstrom_s_lya_l29
- id: '1574871873762'
  alias: Arrive home
  description: ''
  trigger:
  - entity_id: device_tracker.dc_16_b2_af_85_73
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: nu e vi hemma enl device tracker
      title: hemma
    service: notify.mobile_app_victor_ohrstrom_s_lya_l29
