homeassistant:
  # Name of the location where Home Assistant is running
  name: "Tallgatan 9"
  # Location required to calculate the time the sun rises and sets
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  #customize: !include customize.yaml
  # WHITELIST
  whitelist_external_dirs: 
  - /tmp/
  - /config/www/

  latitude: !secret lat
  longitude: !secret long

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.1.0/24
#    - type: legacy_api_password

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

system_health:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: disgaea.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5
  ip_ban_enabled: true

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

#Enable influx DB
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret password_small
  max_retries: 3
  default_measurement: state

recorder:
  purge_keep_days: 7
  purge_interval: 1

ffmpeg:

light:
  - platform: flux_led
    devices:
      192.168.1.111:
        name: House outside back
        mode: "rgbw"
  - platform: flux_led
    devices:
      192.168.1.120:
        name: Tv led
        mode: "rgbw"
  - platform: flux_led
    devices:
      192.168.1.125:
        name: Kitchen strip
        mode: "rgbw"
  - platform: group
    name: Hallen
    entities:
      - light.hallen_1
      - light.hallen_2
      - light.hallen_3
      - light.hallen_4
      - light.hall_uppe_1_2
      - light.hall_uppe_2_2
      - light.hall_uppe_3_2
  - platform: group
    name: Liam
    entities:
      - light.liam_tak_1_2
      - light.liam_tak_2_2
      - light.liam_tak_3_2
  - platform: group
    name: Kontoret
    entities:
      - light.kontoret_tak_1
      - light.kontoret_tak_2
      - light.kontoret_tak_3
  - platform: group
    name: "Tv rum"
    entities:
      - light.tvrum_tak
      - light.family_room_1
      - light.family_room_2
      - light.family_room_3
      - light.light_strip_switch
  - platform: group
    name: "Köket"
    entities:
      - light.kok_1
      - light.kok_2
      - light.kok_spot_1
      - light.kok_spot_2
      - light.kok_spot_3
  - platform: group
    name: "Sovrum"
    entities:
      - light.sovrum_1
      - light.sovrum_2

camera:
  - platform: onvif
    name: 'Cam 1'
    host: 192.168.1.126
    port: 8080
    username: admin
    password: !secret password_small
    profile: 1

# Weather prediction
sensor:
  - platform: sma
    host: 192.168.1.124
    ssl: true
    verify_ssl: false
    password: !secret password_small
    sensors:
      - current_consumption
      - total_consumption
      - pv_power
      - total_yield
      - daily_yield
      - status
      - current_consumption
    custom:
      yesterday_consumption:
        key: '6400_00543A01'
        unit: kWh
        factor: 1000
  - platform: template
    sensors:
      hallen_current_temperature:
        friendly_name: "Hallen current temp"
        unit_of_measurement: "°C"
        value_template: "{{state_attr('climate.hallen', 'current_temperature')}}"
      hallen_set_temperature:
        friendly_name: "Hallen set temp"
        unit_of_measurement: "°C"
        value_template: "{{state_attr('climate.hallen', 'temperature')}}"
      hallen_state:
        friendly_name: "Hallen state"
        value_template: "{{states('climate.hallen')}}"
  #HA monitor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
  #TRAFIKVERKET
  - platform: trafikverket_weatherstation
    name: Trafikverket Road WeatherStation Dörröd
    api_key: !secret trafik_api_key
    station: Dörröd
    monitored_conditions:
      - air_temp
      - humidity
      - wind_direction
      - wind_direction_text
      - wind_speed

# Text to speech
#tts:
#  - platform: google

#  - platform: wake_on_lan
#    mac_address: !secret pc_mac_address
#    name: "Victor PC"
#    host: 192.168.1.118
#    turn_off:
#      service: hassio.addon_stdin
#      data:
#        addon: core_rpc_shutdown
#        input: victor-pc

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: "04:CF:8C:91:60:79"
      key: !secret xiaomi_pass
      host: 192.168.1.117

weather:
  - platform: darksky
    api_key: !secret darksky_api

tibber:
  access_token: !secret tibber_api_key


climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#customize: !include customize.yaml


# alarm_control_panel: !include alarm.yaml
# panel_custom: !include panel_custom.yaml

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret code
    pending_time: 25
    delay_time: 0
    trigger_time: 600
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

mobile_app:
stream: