homeassistant:
  # Name of the location where Home Assistant is running
  name: Tallgatan9
  # Location required to calculate the time the sun rises and sets
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  # WHITELIST
  whitelist_external_dirs: /tmp/

  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: disgaea.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

ffmpeg:

light:
  - platform: flux_led
    devices:
      192.168.1.110:
        name: House outside back
        mode: "rgbw"
  - platform: flux_led
    devices:
      192.168.1.120:
        name: Tv led
        mode: "rgbw"

#camera:
#  - platform: xiaomi
#    name: Cam_1
#    host: '192.168.1.116'
#    model: 'xiaofang'
#    password: !secret cam_pass
#    path: /local/cam1
#    ffmpeg_arguments: '-vf scale=800:450'

# Weather prediction
sensor:
  #HA monitor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
  #MQTT
  - platform: mqtt
    state_topic: "home/office"
    name: 'Temperature office'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: "home/office"
    name: 'Humidity office'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
  - platform: mqtt
    state_topic: "home/familyroom"
    name: 'Temperature Family room'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: "home/familyroom"
    name: 'Humidity Family room'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
  #TRAFIKVERKET
  - platform: trafikverket_weatherstation
    name: Trafikverket Road WeatherStation Dörröd
    api_key: !secret trafik_api_key
    station: Dörröd
    monitored_conditions:
      - air_temp
      - humidity
      - wind_direction
      - wind_direction_text
      - wind_speed


google_assistant:
  project_id: !secret google_project_id
  exposed_domains:
    - switch
    - light
    - climate

# Text to speech
#tts:
#  - platform: google

# SWITCH
switch:
  - platform: mqtt
    name: "Bathroom (new)"
    command_topic: "cmnd/sonoff1/power"
    state_topic: "stat/sonoff1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    retain: true
  - platform: wake_on_lan
    mac_address: !secret pc_mac_address
    name: "Victor PC"
    host: 192.168.1.118
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: victor-pc

# Verisure
verisure:
  username: !secret verisure_username
  password: !secret verisure_password

# HTML5 push
notify:
  - name: HTML5_push
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

# Device tracker
device_tracker:
  - platform: google_maps
    username: victorhassio@gmail.com
    password: !secret password_small

# ZONES
# !include zones.yaml
zone:
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 150
    icon: mdi:work

  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 150
    icon: mdi:account-multiple


mqtt:
  broker: core-mosquitto
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

tibber:
  access_token: !secret tibber_api_key

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key


panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: http://disgaea.duckdns.org:1880



group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
