homeassistant:
  # Name of the location where Home Assistant is running
  name: "Tallgatan 9"
  # Location required to calculate the time the sun rises and sets
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  #customize: !include customize.yaml
  # WHITELIST
  whitelist_external_dirs: 
  - /tmp/
  - /config/www/

  latitude: !secret lat
  longitude: !secret long

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.1.0/24
#    - type: legacy_api_password

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

system_health:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: disgaea.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5
  ip_ban_enabled: true

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

recorder:
  purge_keep_days: 7
  purge_interval: 1

ffmpeg:

light:
  - platform: flux_led
    devices:
      192.168.1.111:
        name: House outside back
        mode: "rgbw"
  - platform: flux_led
    devices:
      192.168.1.120:
        name: Tv led
        mode: "rgbw"
  - platform: flux_led
    devices:
      192.168.1.125:
        name: Kitchen strip
        mode: "rgbw"

camera:
  - platform: onvif
    name: 'Cam 1'
    host: 192.168.1.126
    port: 8080
    username: admin
    password: !secret password_small
    profile: 1


#camera:
#  - platform: generic
#    name: Cam 1
#    still_image_url: http://192.168.1.128/jpg/image.jpg
#    stream_source: rtsp://192.168.1.128:554


#camera:
#  - platform: generic
#    still_image_url: http://194.218.96.92/jpg/image.jpg
#    name: Cam_1
#    host: '192.168.1.116'
#    model: 'xiaofang'
#    password: !secret cam_pass
#    path: /local/cam1
#    ffmpeg_arguments: '-vf scale=800:450'

# Weather prediction
sensor:
  - platform: sma
    host: 192.168.1.124
    ssl: true
    verify_ssl: false
    password: !secret password_small
    sensors:
      - current_consumption
      - total_consumption
      - pv_power
      - total_yield
      - daily_yield
      - status
      - current_consumption
    custom:
      yesterday_consumption:
        key: '6400_00543A01'
        unit: kWh
        factor: 1000
  - platform: template
    sensors:
      hallen_current_temperature:
        friendly_name: "Hallen current temp"
        unit_of_measurement: "°C"
        value_template: "{{state_attr('climate.hallen', 'current_temperature')}}"
      hallen_set_temperature:
        friendly_name: "Hallen set temp"
        unit_of_measurement: "°C"
        value_template: "{{state_attr('climate.hallen', 'temperature')}}"
      hallen_state:
        friendly_name: "Hallen state"
        value_template: "{{states('climate.hallen')}}"
  #HA monitor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
  #MQTT
  - platform: mqtt
    state_topic: "home/office"
    name: 'Temperature office'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: "home/office"
    name: 'Humidity office'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
  - platform: mqtt
    state_topic: "home/familyroom"
    name: 'Temperature Family room'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: "home/familyroom"
    name: 'Humidity Family room'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
  #TRAFIKVERKET
  - platform: trafikverket_weatherstation
    name: Trafikverket Road WeatherStation Dörröd
    api_key: !secret trafik_api_key
    station: Dörröd
    monitored_conditions:
      - air_temp
      - humidity
      - wind_direction
      - wind_direction_text
      - wind_speed
  - platform: trafikverket_train
    api_key: !secret trafik_api_key
    trains:
    - name: "Train to work"
      from: Sölvesborg
      to: Kristianstad C
      time: "07:28"
      weekday: [mon, tue, wed, thu, fri]

# Text to speech
#tts:
#  - platform: google

# SWITCH
switch:
  - platform: mqtt
    name: "Bathroom (new)"
    command_topic: "cmnd/sonoff1/power"
    state_topic: "stat/sonoff1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    retain: true
#  - platform: wake_on_lan
#    mac_address: !secret pc_mac_address
#    name: "Victor PC"
#    host: 192.168.1.118
#    turn_off:
#      service: hassio.addon_stdin
#      data:
#        addon: core_rpc_shutdown
#        input: victor-pc

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: "04:CF:8C:91:60:79"
      key: !secret xiaomi_pass
      host: 192.168.1.117

weather:
  - platform: darksky
    api_key: !secret darksky_api

# HTML5 push
notify:
  - name: HTML5_push
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

#hue:
#  bridges:
#    - host: 192.168.1.115

tibber:
  access_token: !secret tibber_api_key

mqtt:
  broker: core-mosquitto
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password


climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

#device_tracker:
#  - platform: traccar
#    host: a0d7b954-traccar
#    port: 8072
#    username: victor
#    password: !secret password_small


#panel_iframe:
#  nodered:
#    title: Node-RED
#    icon: mdi:sitemap
#    url: https://disgaea.duckdns.org:1880
#  portainer:
#    title: Portainer
#    icon: mdi:docker
#    url: https://disgaea.duckdns.org:9000



group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#customize: !include customize.yaml


# alarm_control_panel: !include alarm.yaml
# panel_custom: !include panel_custom.yaml

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret code
    pending_time: 25
    delay_time: 0
    trigger_time: 600
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0


tradfri:
  host: 192.168.1.107

#notify_hasskit: 
#  token:
#    - !secret notify_token

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.100-105
#    home_interval: 10

mobile_app:
stream: