title: Tallgatan 9
views:
  - title: Main
    id: main
    theme: dark-mode
    cards:
      - type: entities
        title: Office
        entities:
          - light.office
          - sensor.temperature_office
          - sensor.humidity_office
          - device_tracker.google_maps_116101876784266767195
      - type: entities
        title: TV-rum
        entities:
          - light.family_room
          - sensor.temperature_family_room
          - sensor.humidity_family_room
          - media_player.family_room_tv
      - type: entities
        title: Bedroom
        entities:
          - light.liam_lamp
          - light.sovrum_victor
          - light.bedroom
          - media_player.vardagsrummet
      - type: picture-elements
        image: /local/floor1-sm.jpg
        elements:
          - type: state-icon
            tap_action: toggle
            entity: light.family_room
            style:
              top: 10%
              left: 5%
          - type: state-label
            entity: sensor.koket_temperature
            style:
              top: 50%
              left: 50%
      - type: picture-elements
        image: /local/floor2-sm.jpg
        elements:
          - type: state-icon
            tap_action: toggle
            entity: light.office
            style:
              top: 50
              left: 20
