name: Tallgatan 9
views:
  - name: Main
    theme: dark-mode
    cards:
      - type: entities
        title: Office
        entities:
          - light.office
          - sensor.temperature_office
          - sensor.humidity_office
          - device_tracker.google_maps_116101876784266767195
