title: Tallgatan 9
views:
  - title: Main
    id: main
    theme: dark-mode
    cards:
      - type: picture-elements
        image: /local/floor1-sm.jpg
        elements:
          - type: state-icon
            tap_action: toggle
            entity: light.family_room
            style:
              top: 50%
              left: 50%
