title: Tallgatan 9
views:
  - title: Main
    id: main
    theme: dark-mode
    cards:
      - type: entities
        title: TV-rum
        entities:
          - light.family_room
          - sensor.temperature_family_room
          - sensor.humidity_family_room
          - media_player.family_room_tv
      - type: entities
        title: Office
        entities:
          - light.office
          - sensor.temperature_office
          - sensor.humidity_office
          - device_tracker.google_maps_116101876784266767195
      - type: entities
        title: Bedroom
        entities:
          - light.liam_lamp
          - light.sovrum_victor
          - light.bedroom
          - media_player.vardagsrummet
      - type: picture-elements
        image: /local/floor1-sm.jpg
        elements:
          - type: state-icon
            tap_action: toggle
            entity: light.family_room_roof
            style:
              top: 27%
              left: 20%
          - type: state-icon
            tap_action: toggle
            entity: light.family_room
            style:
              top: 35%
              left: 12%
          - type: state-label
            entity: sensor.koket_temperature
            style:
              top: 50%
              left: 40%
          - type: state-badge
            entity: media_player.family_room_tv
            style:
              top: 28%
              left: 28%
          - type: state-badge
            entity: binary_sensor.altandorr
            style:
              top: 85%
              left: 40%
          - type: state-badge
            entity: binary_sensor.huvudingang
            style:
              top: 12%
              left: 46%
      - type: picture-elements
        image: /local/floor2-sm.jpg
        elements:
          - type: state-icon
            tap_action: toggle
            entity: light.office
            style:
              top: 55%
              left: 30%
          - type: state-label
            entity: sensor.temperature_office
            style:
              top: 70%
              left: 30%
